# Generated by Django 3.1 on 2020-09-09 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='名無しさん', max_length=15, null=True, verbose_name='名前')),
                ('text', models.CharField(max_length=300, verbose_name='本文')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('response_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.posts')),
            ],
            options={
                'db_table': 'response',
            },
        ),
    ]
