# Generated by Django 3.1 on 2020-08-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posts',
            table=None,
        ),
    ]
