# Generated by Django 3.1 on 2020-08-23 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20200823_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
