# Generated by Django 3.1 on 2020-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20200823_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='nickname',
            field=models.CharField(max_length=15, null=True, verbose_name='名前'),
        ),
    ]
