# Generated by Django 3.1 on 2020-09-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20200910_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='response_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
