# Generated by Django 3.1 on 2020-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20200823_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
