# Generated by Django 3.1 on 2020-09-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20200911_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='response_id',
        ),
    ]
