# Generated by Django 3.1 on 2020-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20200824_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='nickname',
            field=models.CharField(default='名無しさん', max_length=15, verbose_name='名前'),
        ),
    ]
