# Generated by Django 3.1 on 2020-09-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_remove_posts_response_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='response_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
