# Generated by Django 3.1 on 2020-09-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_auto_20200912_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='response_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
