# Generated by Django 3.1 on 2020-08-29 03:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_auto_20200824_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='スレッド名')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
            options={
                'db_table': 'thread',
            },
        ),
        migrations.RemoveField(
            model_name='posts',
            name='created_at',
        ),
        migrations.AddField(
            model_name='posts',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
        migrations.AddField(
            model_name='posts',
            name='thread_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_app.thread'),
        ),
    ]
